### ISSUE TITLE
Definition of LogMessage is missing in YSFParrot UDPSocket.cpp

### ISSUE THREAD

**Issue by dl1mx** [g4klx/YSFClients#232]
With the last commit 81170f5 the file UDPSocket.cpp does not compile anymore, because the definition of LogMessage is missing.

```
c++ -g -O3 -Wall -std=c++0x -pthread -c -o UDPSocket.o UDPSocket.cpp
UDPSocket.cpp: In member function ‘int CUDPSocket::read(unsigned char*, unsigned int, sockaddr_storage&, unsigned int&)’:
UDPSocket.cpp:294:4: error: ‘LogMessage’ was not declared in this scope
    LogMessage("Re-opening UDP port on %u", m_port);
    ^~~~~~~~~~
make: *** [Makefile:15: UDPSocket.o] Fehler 1

```

**Comment by g4klx** [comment]
Should be fixed now, do another pull please.

    On Monday, 2 November 2020, 14:17:34 GMT, Marco Kubon <notifications@github.com> wrote:  
 
 


With the last commit 81170f5 the file UDPSocket.cpp does not compile anymore, because the definition of LogMessage is missing.
c++ -g -O3 -Wall -std=c++0x -pthread -c -o UDPSocket.o UDPSocket.cpp
UDPSocket.cpp: In member function ‘int CUDPSocket::read(unsigned char*, unsigned int, sockaddr_storage&, unsigned int&)’:
UDPSocket.cpp:294:4: error: ‘LogMessage’ was not declared in this scope
    LogMessage("Re-opening UDP port on %u", m_port);
    ^~~~~~~~~~
make: *** [Makefile:15: UDPSocket.o] Fehler 1

**Comment by dl1mx** [comment]
Works for me now. Thanks.
